version: '3.7'

services:
  rabbitmq:
    image: rabbitmq:3-management
    hostname: rabbitmq
    volumes:
      - ./rabbitmq/etc/definitions.json:/etc/rabbitmq/definitions.json
      - ./rabbitmq/etc/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
      - ./rabbitmq/data:/var/lib/rabbitmq/mnesia/rabbit@my-rabbit
      - ./rabbitmq/logs:/var/log/rabbitmq/log
    ports:
      - 5672:5672
      - 15672:15672

  app: &app
    build:
      context: .
    volumes:
      - .:/var/www/app
      - bundle_path:/bundle
    environment:
      - RAILS_ENV=${RAILS_ENV:-development}
      - DATABASE_URL=postgresql://postgres:postgres@postgres/messages_development
    depends_on:
      - postgres
    tmpfs:
      - /tmp

  runner:
    <<: *app
    stdin_open: true
    tty: true
    command: /bin/bash
    networks:
      default:
      internal:

  runner_tests:
    <<: *app
    stdin_open: true
    tty: true
    command: echo "off by default"
    shm_size: '2gb'
    networks:
      default:
      internal:
    environment:
      - RAILS_ENV=${RAILS_ENV:-test}
      - DATABASE_URL=postgresql://postgres:postgres@postgres/messages_test

  server:
    <<: *app
    stdin_open: true
    tty: true
    command: bundle exec foreman start -f Procfile.dev
    networks:
      default:
      internal:
        aliases:
          - backend-server
    ports:
      - '3035:3035'
      - '5000:5000'

  postgres:
    image: postgres:12.2-alpine
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
  
  redis:
    image: "redis:alpine"
    hostname: redis
    ports:
      - "6379:6379"
    networks:
        default:
        internal:

volumes:
  postgres:
  bundle_path:

networks:
  internal:
